version: "3"
services:
  SonarQube:
    image: sonarqube:latest


    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonartest
      SONAR_JDBC_USERNAME: sonartest
      SONAR_JDBC_PASSWORD: sonartest
    volumes:

      - SonarQube_data:/opt/SonarQube/data
      - SonarQube_extensions:/opt/SonarQube/extensions
      - SonarQube_logs:/opt/SonarQube/logs
      - sonarQube_repo:/opt/SonarQube/myrepo
      - /opt/SonarQube/myrepo:/build

    ports:
      - "9000:9000"


  db:
    image: postgres:12

    environment:
      POSTGRES_USER: sonartest
      POSTGRES_PASSWORD: sonartest

    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
  sonarscanner:
    container_name: sonarscanner
    image:  sonarsource/sonar-scanner-cli
    network_mode: "host"

    volumes:
      - D:/assesment/101digital/coffee_outlet-assessment:/usr/src


volumes:
  SonarQube_data:
  SonarQube_extensions:
  SonarQube_logs:
  postgresql:
  postgresql_data:
  sonarQube_repo:
